-- Seed data — intentionally empty after the workspaces RLS flip.
--
-- /dev/* now reads the mock provider (src/data/mock.ts), so the local
-- Supabase no longer needs fixture clients. /app/* data comes from real
-- auth + onboarding flows, not from a static seed.
--
-- If you need demo data while exercising /app, sign up locally and create
-- a workspace through the onboarding wizard.
